# Generated by Django 2.1.2 on 2018-11-02 10:00

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181102_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=builtins.print, max_length=100),
            preserve_default=False,
        ),
    ]
